language: node_js
node_js: 8
sudo: required

services:
  - mongodb
  - docker

script:
  - npm test
  - docker build -t jtalton/node-mongo-rest-server .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jtalton/node-mongo-rest-server;
    fi
